### ISSUE TITLE
Improving the desktop link - removing link code

### ISSUE THREAD

**Issue by Stefanuk12** [tybayn/phasmo-cheat-sheet#19]
At the moment, you have to use a desktop link code, but this is not needed. The desktop app can create a WebSocket server, and the website can attempt to link to that instead via localhost. Using this approach, it makes it easier to connect. Also, a "connect" button could be added above the save and reset button meaning someone could easily get started within two button clicks: open the application and press connect.

Of course, this is not necessary, but it would reduce load on your servers. You would lose the live members count with this approach unfortunately and if you find this feature very useful, then this approach should not be implemented.

**Comment by tybayn** [comment]
Hey!

So couple points to make here:

1. First and foremost, this is not an issue. Suggestions should be made in the #suggestions channel on my discord server.

2. The reason I keep things like this on the server side is because there is additional logic handling and logging that occurs, plus it ensures that disconnects are handled gracefully. Running local could open up a whole new set of issues where it doesn't work for some people, firewalls get in the way, lots of permissions errors trying to get a website to talk locally.

3. I didn't want to lock down everything to a single machine. I sometimes have my cheat sheet open on a different machine than I'm actually playing the game on (like having an ipad on the side)

4. I haven't ever had issues with it being routed through the servers, and I don't see stress on my system hardly ever.

5. On a plus side, the desktop link is not related to the live number of users in any way, so it wouldn't make that kind of impact.

**Comment by Stefanuk12** [comment]
Yeah I completely understand that no worries. However, you should let people put labels on issues lol, so I could've labelled the issue as an enhancement.
